name: trivy-scan
on:
  schedule:
    - cron: "00 8 * * *" # build at 8:00 UTC every day 
                         # 120 minutes after bluebuild images start building
  workflow_run:
    workflows: ["bluebuild"]
    types:
      - completed

  workflow_dispatch: # allow manually triggering builds
jobs:
  build:
    name: Trivy
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - desktop-gnome
          - desktop-gnome-wrk
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # v0.31.0
        with:
          image-ref: 'ghcr.io/thorsteinbn/${{ matrix.image }}:latest'
          format: template
          scanners: vuln,secret,misconfig
          template: '@/contrib/sarif.tpl'
          output: trivy-results-${{ matrix.image }}.sarif
          timeout: 30m0s
          skip-dirs: "/sysroot/ostree"
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
        with:
          sarif_file: trivy-results-${{ matrix.image }}.sarif
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Trivy scan SARIF ${{ matrix.image }}
          path: trivy-results-${{ matrix.image }}.sarif